# docker-compose.yml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: doctor-portal-dev
    ports:
      - "80:80"
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/client/node_modules
      - /app/server/node_modules
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doctordb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=dev_secret_key
      - PORT=5000

  postgres:
    image: postgres:15
    container_name: doctor-portal-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=doctordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: doctor-portal-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
