# docker-compose.prod.yml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: doctor-portal-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doctordb
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: doctor-portal-postgres
    restart: always
    environment:
      - POSTGRES_DB=doctordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: doctor-portal-redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
